-- ScamFlow Supabase 전체 스키마. 같은 내용은 supabase/migrations 아래에서도 관리합니다.
CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;

CREATE TABLE IF NOT EXISTS public.scam_documents (
    id TEXT PRIMARY KEY,
    agency TEXT NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    source_url TEXT NOT NULL,
    phone TEXT,
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    embedding extensions.vector(256),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.official_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency TEXT NOT NULL,
    phone TEXT NOT NULL,
    normalized_phone TEXT NOT NULL UNIQUE,
    source_url TEXT NOT NULL,
    verified_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.scam_sessions (
    session_id TEXT PRIMARY KEY,
    user_id TEXT,
    state JSONB NOT NULL DEFAULT '{}'::jsonb,
    situation_stage TEXT NOT NULL DEFAULT 'received_message',
    risk_level TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.tool_audit_logs (
    id UUID PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES public.scam_sessions(session_id) ON DELETE CASCADE,
    tool_name TEXT NOT NULL,
    status TEXT NOT NULL,
    summary TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS scam_sessions_updated_at_idx ON public.scam_sessions(updated_at DESC);
CREATE INDEX IF NOT EXISTS tool_audit_logs_session_idx ON public.tool_audit_logs(session_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.match_scam_documents(
    query_embedding extensions.vector(256),
    match_count integer DEFAULT 3
)
RETURNS TABLE (
    id TEXT,
    agency TEXT,
    title TEXT,
    content TEXT,
    source_url TEXT,
    phone TEXT,
    similarity FLOAT
)
LANGUAGE sql STABLE
SET search_path = ''
AS $$
    SELECT d.id, d.agency, d.title, d.content, d.source_url, d.phone,
           1 - (d.embedding OPERATOR(extensions.<=>) query_embedding) AS similarity
    FROM public.scam_documents AS d
    WHERE d.embedding IS NOT NULL
    ORDER BY d.embedding OPERATOR(extensions.<=>) query_embedding
    LIMIT match_count;
$$;

INSERT INTO public.official_contacts (agency, phone, normalized_phone, source_url)
VALUES
    ('경찰청 범죄신고', '112', '112', 'https://www.police.go.kr/'),
    ('한국인터넷진흥원 상담', '118', '118', 'https://www.kisa.or.kr/118'),
    ('검찰청 콜센터', '1301', '1301', 'https://www.spo.go.kr/'),
    ('금융감독원 상담', '1332', '1332', 'https://www.fss.or.kr/'),
    ('서민금융진흥원', '1397', '1397', 'https://www.kinfa.or.kr/')
ON CONFLICT (normalized_phone) DO UPDATE
SET agency = EXCLUDED.agency, phone = EXCLUDED.phone, source_url = EXCLUDED.source_url;

ALTER TABLE public.scam_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.official_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scam_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tool_audit_logs ENABLE ROW LEVEL SECURITY;

-- 서버는 service_role key만 사용합니다. 브라우저 anon key에는 세션/로그 접근 정책을 열지 않습니다.
GRANT SELECT, INSERT, UPDATE, DELETE ON public.scam_documents TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.official_contacts TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.scam_sessions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tool_audit_logs TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
GRANT EXECUTE ON FUNCTION public.match_scam_documents(extensions.vector, integer) TO service_role;
